#+TITLE:   \large STAT 1234 | SOME STATISTICS CLASS | SPRING 2011 | KERNS
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+DATE:      Sample Quiz Template
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:nil ^:nil author:nil
#+EXPORT_EXCLUDE_TAGS: answer
#+BABEL: :session *R* :results raw
#+LaTeX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \input{examformat}

#+begin_src R :exports none :tangle yes
set.seed(42)
#+end_src

#+begin_latex
\begin{flushright}
Name: \underbar{\makebox[2in]{}}
\par
\end{flushright}
\vspace{0.1in}
#+end_latex

\noindent *Directions:[fn:1]*   SHOW ALL WORK. You may use \textsf{R} for computations, but no other software (and in particular, not the Internet). If you use \textsf{R} to calculate something, then hand write the \textsf{R} code that you typed, together with the numerical answer.

[fn:1] more questions on the back.

* The following table categorizes a group of people based on the flavor of Kool-Aid they drink and whether or not they like President Barack Obama.

#+begin_src R :exports none :results output :tangle yes
l <- sample(100, size = 3)
nl <- sample(100, size = 3)
A <- matrix(c(l, nl), nrow = 2, byrow = TRUE)
colnms <- c("grape", "orange", "cherry")
rownms <- c("likes Obama", "doesn't like Obama")
cindx <- sample(3, size = 2, replace = TRUE)
rindx <- sample(2, size = 2, replace = TRUE)
#+end_src

  |                                     | SRC_R[:results scalar]{colnms[1]}      | SRC_R[:results scalar]{ colnms[2] } | SRC_R[:results scalar]{ colnms[3] } | Total                                  |
  |-------------------------------------+----------------------------------------+-------------------------------------+-------------------------------------+----------------------------------------|
  | SRC_R[:results scalar]{ rownms[1] } | SRC_R[:results scalar]{ A[ 1,1 ] }     |                                     | SRC_R[:results scalar]{ A[ 1,3 ] }  | SRC_R[:results scalar]{ sum(A[ 1, ]) } |
  | SRC_R[:results scalar]{ rownms[2] } |                                        | SRC_R[:results scalar]{ A[ 2,2 ] }  |                                     |                                        |
  |-------------------------------------+----------------------------------------+-------------------------------------+-------------------------------------+----------------------------------------|
  | Total                               | SRC_R[:results scalar]{ sum(A[ ,1 ]) } |                                     |                                     | SRC_R[:results scalar]{ sum(A) }       |

Our experiment will be to select one (1) person from the table out of the SRC_R{ sum(A) } people, at random.  


** Fill in the table.

*** 								     :answer:
The completed table looks like this:
  
  |                                     | SRC_R[:results scalar]{colnms[1]}      | SRC_R[:results scalar]{ colnms[2] }    | SRC_R[:results scalar]{ colnms[3] }    | Total                                  |
  |-------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------|
  | SRC_R[:results scalar]{ rownms[1] } | SRC_R[:results scalar]{ A[ 1,1 ] }     | SRC_R[:results scalar]{ A[ 1,2 ] }     | SRC_R[:results scalar]{ A[ 1,3 ] }     | SRC_R[:results scalar]{ sum(A[ 1, ]) } |
  | SRC_R[:results scalar]{ rownms[2] } | SRC_R[:results scalar]{ A[ 2,1 ] }     | SRC_R[:results scalar]{ A[ 2,2 ] }     | SRC_R[:results scalar]{ A[ 2,3 ] }     | SRC_R[:results scalar]{ sum(A[ 2, ]) } |
  |-------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------|
  | Total                               | SRC_R[:results scalar]{ sum(A[ ,1 ]) } | SRC_R[:results scalar]{ sum(A[ ,2 ]) } | SRC_R[:results scalar]{ sum(A[ ,3 ]) } | SRC_R[:results scalar]{ sum(A) }       |


** What is the probability that the person likes SRC_R{ colnms[ cindx[1] ] } Kool-Aid?

*** 								     :answer:
\[
\frac{\mbox{\#( SRC_R{ colnms[ cindx[1] ] } )}}{\mbox{Total \# of people}} =
\frac{ SRC_R{ sum( A[ , cindx[1] ]) } }{ SRC_R{ sum(A) } }\approx SRC_R{ round( sum( A[ , cindx[1] ] )/ sum(A) , 3) }.
\]


** What is the conditional probability that the person likes SRC_R{ colnms[ cindx[ 2 ] ] } Kool-Aid, given that the person SRC_R{ rownms[ rindx[ 2 ] ] }?

*** 								     :answer:
\[
\P( \mbox{ SRC_R{ colnms[ cindx[2] ] } } | \mbox{ SRC_R{ rownms[ rindx[2] ] } } ) =
\frac{\P( \mbox{ SRC_R{ colnms[ cindx[2] ] } and SRC_R{ rownms[ rindx[2] ] } } )}{\P(\mbox{ SRC_R{ rownms[ rindx[2] ] } } ) } = 
\frac{ SRC_R{ A[ rindx[2] , cindx[2] ] } }{ SRC_R{  sum(A[ rindx[2], ])  } }
\approx SRC_R{ round( A[ rindx[2] , cindx[2] ] / sum( A[ rindx[2], ] ), 3) }.
\]



* We would like to feed baby ``Aidan''. At the dinner table, we get a spoon of food and make an airplane /swoop/ as we move the spoon toward his mouth. 

#+begin_src R :exports none :results output :tangle yes
r <- as.double(sample(3:9, size = 1))
pr <- sample(11:49, size = 1)/100
disxs <- sort(rnbinom(10, size = r, prob = pr))
#+end_src

Calling the event \( E=\left\{ \mbox{take a bite}\right\} \) a ``success'', it has been determined by experimentation that on any given airplane swoop, the probability of success is \(p \approx SRC_R{ pr }\). Suppose that Aidan is in the high chair. Let $Y$ denote the number of failed swoops (\(E^{c}=\left\{ \mbox{no bite}\right\}\)) before the first SRC_R{r} successful bites.


** If the successive swoops were to constitute independent Bernoulli trials, what would be the distribution of \(Y\)? You should write the family name of the distribution and numerical value(s) of any parameter(s).

*** 								     :answer:

\begin{studinpt}
library(distr)  \\
Y <- Nbinom(size = SRC_R{r}, prob = SRC_R{pr})
\end{studinpt}

#+begin_src R :exports none :tangle yes
library(distrEx)
Y <- Nbinom(size = r, prob = pr)
#+end_src


** Sketch the probability mass function of $Y$ (roughly). It does not have to be exact, but it should have the right support, be centered in the right place, and have the correct basic spread and shape.


*** 								     :answer:

#+CAPTION:    Plot of the probability mass function
#+LABEL:      fig:yplot
#+ATTR_LaTeX: width=2in, height=2in, placement=[h!]
#+begin_src R :exports both :results output graphics :file plotY.png :tangle yes
plot(Y, to.draw.arg = "d")
#+end_src


** Find the mean and variance of $Y$, denoted $\E Y$ and $\mathrm{Var}(Y)$, by any method you like.

*** 								     :answer:

#+begin_src R :exports both :results output pp :tangle yes
library(distrEx)
E(Y)
var(Y)
#+end_src
